name: Run unit tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [21]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Run unit tests
      run: mvn -B test --file poml.xml